### ISSUE TITLE
Ether delivery via the `SELFDESTRUCT` opcode.

### ISSUE THREAD

**Issue by Dexaran** [fergarrui/ethereum-security#2]
Any contract is intended to receive Ether in `payable` functions only. Thus, there could be contracts that rely on fact that their balance can only be increased through payable functions that are implemented at this contract.

It is not absolutely accurate because it is possible to throw an amount of Ether into a certain address via the SELFDESTRUCT opcode.

```js

contract SuicideDeliverer
{

    function() payable { }

    function deliverTo(address _addr)
    {
        suicide(_addr);
    }
}
```

This can deliver Ether to a contract at `_addr` address without a proper handling. It can violate the internal contract logic, if the contract is based on the assumption that it can only accept Ether properly through calls of "payable" functions.

**Comment by fergarrui** [comment]
This one is already here (maybe the name was not the best):

https://github.com/fergarrui/ethereum-security/blob/master/test/forcether/forceEtherTest.js

Thanks a lot for your suggestions :) Really appreciated.
