### ISSUE TITLE
WithdrawAll function flawed

### ISSUE THREAD

**Issue by joaotbrandao** [fergarrui/ethereum-security#4]
In ReentrancyVulnerableFixed.sol, function WIthdrawAll().

balances[msg.sender] is set to zero before the transaction is made. The variable that should be used is "amount".

**Comment by fergarrui** [comment]
That's very true.
I fixed it here:

https://github.com/fergarrui/ethereum-security/commit/27c7e372b27fabf88549fa14c1dafbbddea83fc5

Thank you very much
